### ISSUE TITLE
Découper les fichiers markdowns (une question = un fichier)

### ISSUE THREAD

**Issue by MarcLoupias** [MarcLoupias/dev.com-faq-git#41]
Une question devrait correspondre à un seul fichier. 

Plus facile de traiter derrière la génération en BBCode pour developpez.com.

Permet aussi de plus facilement générer un sommaire au lieu de l'écrire à la main pour la version Git.

**Comment by mickaelbaron** [comment]
Salut,

Comment vas-tu procéder pour faire une question un fichier ? Quel convention de nommage pour les fichiers souhaites-tu mettre en place ?

Mickael

**Comment by MarcLoupias** [comment]
Je pense que je vais reprendre la numérotation de la FAQ, en gardant la numération basée sur les FAQ SCM existantes sur developpez.com. 

Donc ça pourrait donner quelque chose comme ça : 

```text
faq-content/section-7.1/7.1.q001.md
faq-content/section-7.1/7.1.q002.md
faq-content/section-7.1/...
faq-content/...
faq-content/section-7.3.1/7.3.1.q001.md
faq-content/section-7.3.1/7.3.1.q002.md
faq-content/...
```

La question de l'utilité de l'existance de la section 3 par elle-même se pose. J'avais repris initialement la structure des FAQ existantes (CVS, SVN, ...) mais comme celle-ci est plus fournie ça donne une section 3 sur l'utilisation obèse et déséquilibrée.

Du coup je pense que je vais revoir la structure pour éviter un sous niveau inutile et tout aligner sur le niveau racine ce qui donnerait : 

```text
FAQ Git pour developpez.com

7.1 Généralités
7.2 Installation et configuration
7.3 Initialisation d'un dépôt
7.4 Les dépôts distants (remotes)
7.5 La working directory
7.6 L'index (staging area)
7.7 Les commits
7.8 Les branches
7.9 Les fusions de branches (merge)
7.10 Réécriture de l'historique (rebase)
7.11 Les tags
7.12 Les logs
7.13 Outils
7.14 Contribuer à un projet OpenSource
```

Et en terme de fichiers ça éviterait le sous-niveau de la section 3 : 

```text
faq-content/section-7.1/7.1.q001.md
faq-content/section-7.1/7.1.q002.md
faq-content/section-7.1/...
faq-content/section-7.2/...
faq-content/section-7.3/7.3.q001.md
faq-content/section-7.3/7.3.q002.md
faq-content/section-7.3/...
faq-content/section-7.4/7.4.q001.md
faq-content/section-7.4/...
faq-content/...
```

J'ignore si ça pose en problème au niveau de ce qu'attends developpez en entrée.

En bout de ligne, ça me permet d'utiliser l'outil que je suis entrain de développer (j'ai fini en fait mais il faut que je configure le format de sortie pour les FAQ et que je publie le package sur le registre npm avant de l'utiliser dans ce dépôt) pour générer le BBCode sur la base des fichiers `.md` ce qui donnerait après génération : 

```text
faq-content/section-7.1/7.1.q001.md
faq-content/section-7.1/7.1.q001.bbcode
faq-content/section-7.1/7.1.q002.md
faq-content/section-7.1/7.1.q002.bbcode
faq-content/section-7.1/...
faq-content/section-7.2/...
faq-content/section-7.3/7.3.q001.md
faq-content/section-7.3/7.3.q001.bbcode
faq-content/section-7.3/7.3.q002.md
faq-content/section-7.3/7.3.q002.bbcode
faq-content/section-7.3/...
faq-content/section-7.4/7.4.q001.md
faq-content/section-7.4/7.4.q001.bbcode
faq-content/section-7.4/...
faq-content/...
```

Pour mettre à jour la FAQ il n'y aurait plus qu'à copier coller le BBCode obtenu dans la question qui va bien.

On pourrait ainsi tag ce dépôt et le faire matcher avec un numéro de version de la FAQ pour les mises à jour et gérer un CHANGELOG de la FAQ (ça se gère en automatique via les messages de commits).

Voilà le programme ;)

**Comment by MarcLoupias** [comment]
fixed by #63
